#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: $0 <input_directory>"
    exit 1
fi

input_dir="$1"
output_dir="${input_dir}/out"

mkdir -p "$output_dir"

for file in "$input_dir"/*; do

    if [[ "$file" == *.vst ]]; then
        mode="readin-draw"
        drawt=""
    elif [[ "$file" == *.vrt ]]; then
        mode="result-readin-draw"
        drawt="ALL"
    else
        continue
    fi

    filename=$(basename "$file")
    output_file="${output_dir}/${filename%.*}.png"

    vst_plot "$mode" "$file" "$output_file" "$drawt" &

done

wait
